# Generated by Django 3.0.8 on 2020-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200909_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
